#!/usr/bin/env python3
"""Generates src/catalog.zig.

The gateway decides which models exist and the docs decide which wire serves
each one, so every per-model fact comes from a live source. The output is
committed, so a normal `zig build` needs no network. Run
`python3 tools/gen_catalog.py` to refresh it.
"""

import json
import sys
import urllib.request

MODELS_DEV = "https://models.dev/api.json"

PROVIDERS = [
    {
        "id": "opencode",
        "listing": "https://opencode.ai/zen/v1/models",
        "docs": "https://opencode.ai/docs/zen.md",
    },
    {
        "id": "opencode-go",
        "listing": "https://opencode.ai/zen/go/v1/models",
        "docs": "https://opencode.ai/docs/go.md",
    },
]

# The four wires, as the path suffix that ends their endpoint URL.
SUFFIX_WIRES = [
    ("/chat/completions", "openai-completions"),
    ("/responses", "openai-responses"),
    ("/messages", "anthropic-messages"),
]

# The AI SDK package names the docs and models.dev use for each wire.
NPM_WIRES = {
    "@ai-sdk/openai-compatible": "openai-completions",
    "@ai-sdk/openai": "openai-responses",
    "@ai-sdk/anthropic": "anthropic-messages",
    "@ai-sdk/google": "google-generative-ai",
}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "mini-catalog/1"})
    with urllib.request.urlopen(req) as r:
        return r.read()


def fetch_json(url):
    return json.loads(fetch(url))


def parse_docs(text):
    """Model id -> endpoint URL, from every pipe table row in the docs."""
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 3:
            continue
        endpoint = cells[2]
        if not (endpoint.startswith("`") and endpoint.endswith("`")):
            continue
        endpoint = endpoint[1:-1]
        if endpoint.startswith("http"):
            out[cells[1]] = endpoint
    return out


def wire_of(url, model_id):
    """The wire and the base URL an endpoint URL names, or (None, None)."""
    for suffix, wire in SUFFIX_WIRES:
        if url.endswith(suffix):
            return wire, url[: -len(suffix)]
    google = "/models/" + model_id
    if url.endswith(google):
        return "google-generative-ai", url[: -len(google)]
    return None, None


def zstr(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def effort_of(model):
    for opt in model.get("reasoning_options") or []:
        if opt.get("type") == "effort":
            return opt.get("values") or []
    return []


def resolve(provider, model_id, docs, models_dev):
    """The wire and base URL for one model, or (None, None) when neither the
    docs nor models.dev names a wire and the provider has no usable default."""
    url = docs.get(model_id)
    if url is not None:
        # The docs named an endpoint, so they own the answer: either it is one
        # of the four wires or the model is unaddressable.
        wire, base = wire_of(url, model_id)
        return wire, (base or "").rstrip("/")
    entry = (models_dev.get("models") or {}).get(model_id) or {}
    npm = (entry.get("provider") or {}).get("npm") or (
        provider.get("npm") if "npm" in provider else None
    )
    wire = NPM_WIRES.get(npm)
    base = (provider.get("api") or "").rstrip("/")
    if wire and base.startswith("https://") and "/models/" not in base:
        return wire, base
    return None, None


def entry_line(provider_id, model_id, api, base_url, model):
    limit = model.get("limit") or {}
    cost = model.get("cost") or {}
    effort = effort_of(model)
    if len(effort) == 1:
        eff = "&.{%s}" % zstr(effort[0])
    elif effort:
        eff = "&.{ %s }" % ", ".join(zstr(v) for v in effort)
    else:
        eff = "&.{}"
    return (
        "    .{ .provider = %s, .id = %s, .name = %s, .api = %s, "
        ".base_url = %s, .images = %s, .reasoning = %s, .context = %d, "
        ".max_output = %d, .effort = %s, .cost_input = %s, .cost_output = %s, "
        ".cost_cache_read = %s },"
        % (
            zstr(provider_id),
            zstr(model_id),
            zstr(model.get("name") or model_id),
            zstr(api),
            zstr(base_url),
            "true" if model.get("attachment") else "false",
            "true" if model.get("reasoning") else "false",
            int(limit.get("context") or 0),
            int(limit.get("output") or 0),
            eff,
            repr(float(cost.get("input") or 0)),
            repr(float(cost.get("output") or 0)),
            repr(float(cost.get("cache_read") or 0)),
        )
    )


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "src/catalog.zig"
    models_dev = fetch_json(MODELS_DEV)

    lines = [
        "// Generated by tools/gen_catalog.py. Do not edit.",
        "// Refresh with `python3 tools/gen_catalog.py`.",
        "",
        "const std = @import(\"std\");",
        "",
        "pub const ModelInfo = struct {",
        "    provider: []const u8,",
        "    id: []const u8,",
        "    name: []const u8,",
        "    api: []const u8,",
        "    base_url: []const u8,",
        "    images: bool,",
        "    reasoning: bool,",
        "    context: u64,",
        "    max_output: u64,",
        "    effort: []const []const u8,",
        "    cost_input: f64,",
        "    cost_output: f64,",
        "    cost_cache_read: f64,",
        "};",
        "",
        "pub const entries = [_]ModelInfo{",
    ]

    count = 0
    for spec in PROVIDERS:
        provider_id = spec["id"]
        provider = models_dev.get(provider_id)
        if provider is None:
            sys.exit("catalog: provider %r missing from models.dev" % provider_id)
        docs = parse_docs(fetch(spec["docs"]).decode("utf-8"))
        listing = sorted(m["id"] for m in fetch_json(spec["listing"])["data"])
        catalog = provider["models"]

        skipped = []
        for model_id in listing:
            api, base_url = resolve(provider, model_id, docs, catalog)
            if api is None:
                where = docs.get(model_id)
                skipped.append((model_id, where or "no endpoint"))
                continue
            lines.append(
                entry_line(provider_id, model_id, api, base_url, catalog.get(model_id) or {})
            )
            count += 1

        print("%s: %d models" % (provider_id, len(listing) - len(skipped)))
        for model_id, endpoint in skipped:
            print("  skipped %s (%s)" % (model_id, endpoint), file=sys.stderr)

    lines += [
        "};",
        "",
        "pub fn lookup(provider: []const u8, id: []const u8) ?*const ModelInfo {",
        "    for (&entries) |*e| {",
        "        if (std.mem.eql(u8, e.provider, provider) and std.mem.eql(u8, e.id, id)) return e;",
        "    }",
        "    return null;",
        "}",
        "",
    ]

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d models)" % (out, count))


if __name__ == "__main__":
    main()
