#!/usr/bin/env python3
"""Generates src/catalog.zig from the models.dev catalog.

Run `python3 tools/gen_catalog.py` to refresh it. The output is committed, so a
normal `zig build` needs no network. Override the source with a path or URL and
the output with a second argument.
"""

import json
import sys
import urllib.request

SOURCE = "https://models.dev/api.json"
PROVIDERS = ["opencode", "opencode-go"]


def fetch(src):
    if src.startswith(("http://", "https://")):
        req = urllib.request.Request(src, headers={"User-Agent": "mini-catalog/1"})
        with urllib.request.urlopen(req) as r:
            return json.load(r)
    with open(src) as f:
        return json.load(f)


def zstr(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def effort_of(model):
    for opt in model.get("reasoning_options") or []:
        if opt.get("type") == "effort":
            return opt.get("values") or []
    return []


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else SOURCE
    out = sys.argv[2] if len(sys.argv) > 2 else "src/catalog.zig"
    data = fetch(src)

    lines = [
        "// Generated by tools/gen_catalog.py from models.dev. Do not edit.",
        "// Refresh with `python3 tools/gen_catalog.py`.",
        "",
        "const std = @import(\"std\");",
        "",
        "pub const ModelInfo = struct {",
        "    provider: []const u8,",
        "    id: []const u8,",
        "    name: []const u8,",
        "    images: bool,",
        "    reasoning: bool,",
        "    context: u64,",
        "    max_output: u64,",
        "    effort: []const []const u8,",
        "    cost_input: f64,",
        "    cost_output: f64,",
        "    cost_cache_read: f64,",
        "};",
        "",
        "pub const entries = [_]ModelInfo{",
    ]

    count = 0
    for provider in PROVIDERS:
        p = data.get(provider)
        if not p:
            sys.exit("catalog: provider %r missing from source" % provider)
        for mid in sorted(p["models"]):
            m = p["models"][mid]
            effort = effort_of(m)
            if len(effort) == 1:
                eff = "&.{%s}" % zstr(effort[0])
            elif effort:
                eff = "&.{ %s }" % ", ".join(zstr(v) for v in effort)
            else:
                eff = "&.{}"
            limit = m.get("limit") or {}
            cost = m.get("cost") or {}
            lines.append(
                "    .{ .provider = %s, .id = %s, .name = %s, .images = %s, "
                ".reasoning = %s, .context = %d, .max_output = %d, .effort = %s, "
                ".cost_input = %s, .cost_output = %s, .cost_cache_read = %s },"
                % (
                    zstr(provider),
                    zstr(mid),
                    zstr(m.get("name") or mid),
                    "true" if m.get("attachment") else "false",
                    "true" if m.get("reasoning") else "false",
                    int(limit.get("context") or 0),
                    int(limit.get("output") or 0),
                    eff,
                    repr(float(cost.get("input") or 0)),
                    repr(float(cost.get("output") or 0)),
                    repr(float(cost.get("cache_read") or 0)),
                )
            )
            count += 1

    lines += [
        "};",
        "",
        "pub fn lookup(provider: []const u8, id: []const u8) ?*const ModelInfo {",
        "    for (&entries) |*e| {",
        "        if (std.mem.eql(u8, e.provider, provider) and std.mem.eql(u8, e.id, id)) return e;",
        "    }",
        "    return null;",
        "}",
        "",
    ]

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d models)" % (out, count))


if __name__ == "__main__":
    main()
