#!/usr/bin/env python3
"""Generates src/tui/width_tables.zig from the Unicode Character Database.

Every table is a sorted list of non-overlapping inclusive codepoint ranges, so
lookup is a binary search and a normal `zig build` needs no network. Run
`python3 tools/gen_width.py` to refresh against a newer UCD; the version it
reads is printed and recorded in the file header.
"""

import sys
import urllib.request

BASE = "https://www.unicode.org/Public/UCD/latest/ucd/"

FILES = {
    "eaw": "EastAsianWidth.txt",
    "gc": "extracted/DerivedGeneralCategory.txt",
    "dcp": "DerivedCoreProperties.txt",
    "emoji": "emoji/emoji-data.txt",
    "gbp": "auxiliary/GraphemeBreakProperty.txt",
}


def fetch(name):
    url = BASE + FILES[name]
    try:
        with urllib.request.urlopen(url) as r:
            return r.read().decode("utf-8")
    except Exception as e:  # pragma: no cover
        sys.exit(f"gen_width: cannot fetch {url}: {e}")


def parse(text, field=1):
    """Yields (lo, hi, property) for every non-comment line of a UCD file.

    A line may carry several semicolon fields; `field` picks one, and -1 picks
    the last. The InCB lines of DerivedCoreProperties are `range; InCB; Value`,
    so they are read with field=-1.
    """
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or ";" not in line:
            continue
        parts = [p.strip() for p in line.split(";")]
        rng = parts[0]
        lo, _, hi = rng.partition("..")
        yield int(lo, 16), int(hi or lo, 16), parts[field]


def merge(rows):
    """Sorts and coalesces (lo, hi) pairs into disjoint ranges."""
    rows = sorted(set(rows))
    out = []
    for lo, hi in rows:
        if out and lo <= out[-1][1] + 1:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return [(lo, hi) for lo, hi in out]


def select(rows, wanted):
    return merge([(lo, hi) for lo, hi, prop in rows if prop in wanted])


def classes(rows, wanted):
    """Merges per-property ranges into a distinct-class range list."""
    by_prop = {}
    for lo, hi, prop in rows:
        if prop in wanted:
            by_prop.setdefault(prop, []).append((lo, hi))
    out = []
    for prop, ranges in by_prop.items():
        for lo, hi in merge(ranges):
            out.append((lo, hi, prop))
    out.sort()
    return out


def emit_range(name, ranges):
    body = ",\n".join("    .{ .lo = 0x%X, .hi = 0x%X }" % (lo, hi) for lo, hi in ranges)
    return (
        f"pub const {name} = [_]Range{{\n{body},\n}};\n"
    )


def emit_classes(name, ranges):
    body = ",\n".join(
        "    .{ .lo = 0x%X, .hi = 0x%X, .class = .%s }" % (lo, hi, prop.lower())
        for lo, hi, prop in ranges
    )
    return f"pub const {name} = [_]ClassRange{{\n{body},\n}};\n"


def main():
    eaw = list(parse(fetch("eaw")))
    gc = list(parse(fetch("gc")))
    dcp = list(parse(fetch("dcp")))
    emoji = list(parse(fetch("emoji")))
    gbp = list(parse(fetch("gbp")))

    wide = merge(
        [(lo, hi) for lo, hi, p in eaw if p in ("W", "F")]
        + [(lo, hi) for lo, hi, p in emoji if p in ("Emoji_Presentation", "Emoji_Modifier_Base")]
    )
    zero = merge(
        [(lo, hi) for lo, hi, p in gc if p in ("Mn", "Me", "Cf")]
        + [(lo, hi) for lo, hi, p in dcp if p == "Default_Ignorable_Code_Point"]
        + [(0xFE00, 0xFE0F), (0xE0100, 0xE01EF), (0x200B, 0x200D)]
    )
    emoji_prop = select(emoji, ("Emoji", "Emoji_Modifier_Base"))
    extpict = select(emoji, ("Extended_Pictographic",))
    incb = list(parse(fetch("dcp"), field=-1))
    consonant = merge([(lo, hi) for lo, hi, p in incb if p == "Consonant"])
    linker = merge([(lo, hi) for lo, hi, p in incb if p == "Linker"])
    gbclasses = classes(
        gbp,
        {
            "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
            "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT",
        },
    )

    version = ""
    for line in fetch("eaw").splitlines():
        if line.startswith("# EastAsianWidth-"):
            version = line.split("-")[1].split(".")[:-1]
            version = ".".join(version)
            break

    parts = [
        "// Generated by tools/gen_width.py from the Unicode Character Database.\n",
        f"// EastAsianWidth version {version}. Do not edit by hand.\n\n",
        "pub const Range = struct { lo: u21, hi: u21 };\n",
        "pub const Class = enum { cr, lf, control, extend, zwj, regional_indicator, prepend, spacingmark, l, v, t, lv, lvt };\n",
        "pub const ClassRange = struct { lo: u21, hi: u21, class: Class };\n\n",
        emit_range("wide", wide),
        "\n",
        emit_range("zero", zero),
        "\n",
        emit_range("emoji", emoji_prop),
        "\n",
        emit_range("extended_pictographic", extpict),
        "\n",
        emit_range("consonant", consonant),
        "\n",
        emit_range("linker", linker),
        "\n",
        emit_classes("grapheme", gbclasses),
    ]
    out = "".join(parts)
    with open(sys.argv[1] if len(sys.argv) > 1 else "src/tui/width_tables.zig", "w") as f:
        f.write(out)
    print(f"gen_width: wide={len(wide)} zero={len(zero)} emoji={len(emoji_prop)} "
          f"extpict={len(extpict)} gb={len(gbclasses)} consonant={len(consonant)} linker={len(linker)}")


if __name__ == "__main__":
    main()
